baseURL = 'https://tableauxtheory.com/'
languageCode = 'en-us'
title = 'TABLEAUX THEORY'
theme = 'digio-theme'
disableKinds = ['taxonomy', 'term']
ignoreFiles = ['^open-source/', '^me\\.md$', '^write/']

[menus]
  [[menus.main]]
    name = 'home'
    pageRef = '/'
    weight = 1

  [[menus.main]]
    name = 'log'
    pageRef = '/log'
    weight = 2

  [[menus.main]]
    name = 'phil'
    pageRef = '/philosophy'
    weight = 3

  [[menus.main]]
    name = 'shop'
    pageRef = '/shop'
    weight = 4
